Да, можно. В этом случае блок finally будет выполняться всегда, независимо от того, было ли выброшено исключение в блоке try. 
Это полезно, когда необходимо выполнить какие-либо действия, даже если исключение не возникло или было выброшено. 